### ISSUE TITLE
Need a License

### ISSUE THREAD

**Issue by Devination** [RafaelOliveira/Sdg#9]
Hey @RafaelOliveira, great work on the engine so far, it looks pretty impressive! I was planning on tinkering with the engine but just wanted to be sure I was allowed to first. [Choosealicense.com](https://choosealicense.com/no-license/) states:

> "If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software."

So it'd be nice to have a license explicitly associated with this project so we know for sure. Might I suggest a permissive license such as [MIT](https://tldrlegal.com/license/mit-license)? :)

Also, I'm not a lawyer or anything so I'm not sure but I think since @jrdoughty has also contributed you might both need to agree on the license.

**Comment by RafaelOliveira** [comment]
Hi, thanks for the words. I want the engine to mature and become a good option for other people in the Kha comunnity, like HaxeFlixel is for OpenFL. About the license, some parts of the code was ported from others engines, like Wyngine, HaxePunk and HaxeFlixel. HaxePunk and HaxeFlixel both uses the MIT license, so I will use it too. Wyngine doesnt have a license, so I will ask them if is possible to add one too.

This is my first real engine, and I'm not very experienced, so any suggestion or code contribution is welcome.

So, @jrdoughty do you agree on the MIT license?

**Comment by RafaelOliveira** [comment]
This is the issue in the wyngine repo about the license:
https://github.com/laxa88/wyngine/issues/1

**Comment by jrdoughty** [comment]
Yeah, MIT is a solid choice. Everything I do on Github I put under that so you don't have to worry about my code.

**Comment by RafaelOliveira** [comment]
The license was added.
